### PR TITLE
Switched hard coded translation keys for auto-generated ones

### PR DESCRIPTION
**Pull request by DoctorVanGogh**
Just some future proofing of the translation keys.

Instead of hard/hand-coding every entry in the `Keys.xml` file just auto-generate corresponding fields.

Auto-Generation happens on build or (manual) save of the `.tt` file.

### CODE REVIEW

**Review by tommargar — COMMENTED** [review]
what are the advantages over the vanilla static methods? I mean I barely understand this code, and I can't fix or update what I don't understand.
Are these changes tested on Linux or Mac also?

**Comment by DoctorVanGogh** [comment]
The advantage is you'll never have to touch the code key definitions file _ever again_. Also you don't have to keep a parallel structure to the xml keys. That's work saved, and error possibilities (typos) eliminated.

As for cross-platform - SharpDevelop supports .t4/.tt files since 2011 (http://community.sharpdevelop.net/blogs/mattward/archive/2011/06/26/T4TemplatesInSharpDevelop.aspx) so yeah, that should work.

---

Regarding maintaining this stuff (if you don't know it): Think of T4 (or .tt) as "php/asp, but for c#", except you use c# inside the templating engine, and you can output any type of text (here it's c#).

A _real_ short [introduction to T4](http://www.wittycoding.com/introduction-to-text-templates-t4).

Basically you have a bunch of directives at the top (should be self explanatory). Then everything in the tt file get's written to the output file, _except_
- Stuff between `<#   #>` get's executed
- Stuff between `<#= #>` get's evaluated and written to the output
- Stuff between `<#+ #>` get's added as variables/methods to the execution engine, so you can add utility stuff there.

You can happily mix execution and output blocks.

This particular tt file has the following structure
- processing directives at the top (think `using` statements)
- a short block, where you define 
  - the namespace to use [optional]
  - declare what xml files to process later.
_This is the only place where you'd expect to maybe touch things later on, when you add a second language keys xml file (but why would you?), or maybe if you move files around, you'd change the path(s)_
- Write some header stuff
- for each file queued by `ParseXML` creates a subclass
  - for each xml element inside that file
    - creates a `public const string` in form of `SanitizedKeyName = "KeyName"` (with comments containing the content even)
- utility routines
  - private variables
  - `SetNamespace` & `ParseXML` methods (including overloads) which set up the internal data structures
  -  utility function to sanitize xml element names so they'll return valid c# identifiers (Basically anything that's not okay in c# get's turned into `_`)

---

This auto-generation happens on _every build_. So if you ever add another node inside the language xml file it immediately get's picked up and has a const declared for it.
If you rename a node it updates the corresponding const's value (and name). The build actually won't go through now, you'll have to take a look and rename you variable references accordingly (which I consider a good thing - no more accidental key presses with the xml file open, and you happen to rename a translation key).
Even if you write malformed xml by accident (Rimworld won't scream), you notice, since the tt execution will barf with an error.

I like T4s - they're the fire & forget code generators for csharp.

If you are willing to take a look at T4 you'll need better editor support than vanilla VS. I believe you're using VS2017? Then you could give https://marketplace.visualstudio.com/items?itemName=tangibleengineeringGmbH.tangibleT4Editor240plusmodelingtoolsforVS2017 a try.

**Comment by tommargar** [comment]
do you have more examples of this in practice? it's a very advanced technique and I've never seen an application in any other mod. don't get me wrong, but I'm working on multiple mods in the past years and consider that much effort highly experimental for just replacing a few strings. does it work with 2+ languages? Also Unity tends to clutter up the RAM with stuff generated on runtime. wouldn't be my first mod which finally crashes someone's game.
I've made the experience that things like these tend to backfire, see the outfit search and other weird behaviour. I'd also need to test it in Linux & Mac, as I don't trust anything not tested. 
I really appreciate you effort, but two lines of translation are not worth the trouble for me.

**Comment by DoctorVanGogh** [comment]
You misunderstand:
- This is not something that happens at runtime. This happens on development machines (before) compilation. It's just not some highly evolved monkey typing all the code, but it's generated by a ~~mechanoid AI~~ templating engine.
- The 'amount' of languages is irrelevant. You'd just feed in the definitions for the 'master' language file(s) - which I'd assume would be English.

Regarding fears about Unity, and things not working on other platforms, this has no effect on that. My personal feeling about the outfit search is that something wasn't right with the homebrew detours implementation. With Harmony luckily this should be gone, since that library has far wider usage and even seems to gain a lot of traction outside Rimworld.

For an example, I've pushed a previously private branch of an in-dev mod of mine where I use this. Take a look at [this file](https://github.com/DoctorVanGogh/ReclaimReuseRecycle/blob/reclaim/Source/ReclaimReuseRecycle/DefNames.Generated.cs). Writing this by hand is __work__, and somewhat error prone. Also whenever you'd want to add something, you'd have to keep in mind that there's multiple places to add stuff, not make a typo, etc.
Luckily I don't have to write this by hand. I just have to add _one or more lines_ [here](https://github.com/DoctorVanGogh/ReclaimReuseRecycle/blob/reclaim/Source/ReclaimReuseRecycle/DefNames.Generated.tt#L12-L20). Hell, with a bit of effort I could extend this to give static references to all Defs in `Core`.

And yes, two lines of constants are not worth it. This is not about now, this is about the amount of work for future expansions. 
Ultimately it's not just two lines. It's _any number_ of constants ___in any number of mods___. You can copy that .tt file and paste it verbatim to any of your mods that define xml based localized text. Just change the [generated namespace](https://github.com/DoctorVanGogh/StorageSearch/blob/localizer/Source/Languages/DefGenerator.tt#L14) to whatever you like, and make sure the [path](https://github.com/DoctorVanGogh/StorageSearch/blob/localizer/Source/Languages/DefGenerator.tt#L17) from the .tt file to the `Keys.xml` file resolves correctly. One CTRL-S later you have all the references you've defined.

---

In the end this is not important. It's a highly engineered minuscule part of the project that borders on a Rube-Goldberg contraption for the current scope of this mod. If you don't like it - fine with me.
There are way more functional elements that need way less potential discussion.

**Comment by tommargar** [comment]
I can't compile your version.
LanguageDefs.cs is missing and there are two spelling mistakes of "StorageSearc".

I'm just sceptic with new, untested methods. Have you really compiled and tested the current version?

**Pull request merged**
